# Generated by Django 6.0.1 on 2026-01-16 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_walletnonce'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WalletNonce',
        ),
    ]
